# SPDX-FileCopyrightText: 2022 Frans van Dorsselaer
#
# SPDX-License-Identifier: GPL-3.0-only

---
# yaml-language-server: $schema=https://json.schemastore.org/codecov.json

coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
