# SPDX-FileCopyrightText: 2020 Frans van Dorsselaer
#
# SPDX-License-Identifier: GPL-3.0-only

---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          # NOTE: caching seems to actually slow down the build, both on hit and on miss
          cache: false
          cache-dependency-path: '**/packages.lock.json'

      - name: Install dependencies
        run: |
          dotnet restore
          dotnet restore Installer

      - name: Build
        run: |
          dotnet build --configuration Release --no-restore

      - name: Test
        run: |
          dotnet test --configuration Release --no-build `
            -p:TestingPlatformCommandLineArguments="--report-trx --coverage --coverage-output-format cobertura --coverage-output coverage.cobertura.xml"

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action/windows@v2
        if: always()
        with:
          files: |
            **/TestResults/*.trx

      - name: Codecov
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Build (Installer)
        run: |
          dotnet publish --configuration Release --no-build Usbipd
          dotnet publish --configuration Release --no-build Usbipd.PowerShell
          dotnet build --configuration Release --no-restore Installer

      - name: Upload Installer Artifact
        uses: actions/upload-artifact@v4
        with:
          name: msi-installer
          path: 'Installer/bin/x64/release/*.msi'
