# SPDX-FileCopyrightText: 2020 Frans van Dorsselaer
#
# SPDX-License-Identifier: GPL-2.0-only

name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1
    - name: Install dependencies (Installer)
      run: msbuild Installer -t:restore -p:RestorePackagesConfig=true -p:SolutionDir=$GITHUB_WORKSPACE
    - name: Build (Installer)
      run: msbuild Installer
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: msi-installer
        path: "Installer/bin/release/*.msi"
