# SPDX-FileCopyrightText: 2023 Frans van Dorsselaer
#
# SPDX-License-Identifier: GPL-3.0-only

---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: winget

on:
  workflow_dispatch:
  release:
    types: [released]

permissions: read-all

jobs:
  publish:
    runs-on: windows-latest

    steps:
      # Commit - docs: add dorssel as a contributor for bug (#303)
      # Date & Time - June 28, 2024 11:03 PM GMT+5:30
      - uses: vedantmgoyal9/winget-releaser@a2ac6c7691dd063a6f6e782fdd11090f5ab45525
        with:
          identifier: dorssel.usbipd-win
          token: ${{ secrets.WINGET_TOKEN }}
